db.type=postgresql
db.username=i2b2metadata
db.password=demouser
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/i2b2
db.project=demo
db.dimension=OBSERVATION_FACT
db.schemaname=I2B2DEMODATA
