CREATE USER i2b2demodata IDENTIFIED BY demouser;
CREATE USER i2b2hive IDENTIFIED BY demouser;
CREATE USER i2b2imdata IDENTIFIED BY demouser;
CREATE USER i2b2metadata IDENTIFIED BY demouser;
CREATE USER i2b2pm IDENTIFIED BY demouser;
CREATE USER i2b2workdata IDENTIFIED BY demouser;

GRANT ALL PRIVILEGES TO i2b2demodata;
GRANT ALL PRIVILEGES TO i2b2hive;
GRANT ALL PRIVILEGES TO i2b2imdata;
GRANT ALL PRIVILEGES TO i2b2metadata;
GRANT ALL PRIVILEGES TO i2b2pm;
GRANT ALL PRIVILEGES TO i2b2workdata;

COMMIT;

exit;
