-- POSTGRESQL
CREATE DATABASE i2b2;
CREATE USER i2b2demodata WITH PASSWORD 'demouser';
CREATE USER i2b2hive WITH PASSWORD 'demouser';
CREATE USER i2b2imdata WITH PASSWORD 'demouser';
CREATE USER i2b2metadata WITH PASSWORD 'demouser';
CREATE USER i2b2pm WITH PASSWORD 'demouser';
CREATE USER i2b2workdata WITH PASSWORD 'demouser';
GRANT ALL PRIVILEGES ON DATABASE i2b2 TO i2b2demodata;
GRANT ALL PRIVILEGES ON DATABASE i2b2 TO i2b2hive;
GRANT ALL PRIVILEGES ON DATABASE i2b2 TO i2b2imdata;
GRANT ALL PRIVILEGES ON DATABASE i2b2 TO i2b2metadata;
GRANT ALL PRIVILEGES ON DATABASE i2b2 TO i2b2pm;
GRANT ALL PRIVILEGES ON DATABASE i2b2 TO i2b2workdata;
GRANT ALL PRIVILEGES ON DATABASE i2b2 TO i2b2demodata;

-- SQLSERVER
-- CREATE DATABASE i2b2;
-- CREATE LOGIN i2b2demodata WITH PASSWORD = 'demouser',CHECK_POLICY=OFF,CHECK_EXPIRATION=OFF;
-- CREATE LOGIN i2b2hive WITH PASSWORD = 'demouser',CHECK_POLICY=OFF,CHECK_EXPIRATION=OFF;
-- CREATE LOGIN i2b2imdata WITH PASSWORD = 'demouser',CHECK_POLICY=OFF,CHECK_EXPIRATION=OFF;
-- CREATE LOGIN i2b2metadata WITH PASSWORD = 'demouser',CHECK_POLICY=OFF,CHECK_EXPIRATION=OFF;
-- CREATE LOGIN i2b2pm WITH PASSWORD = 'demouser',CHECK_POLICY=OFF,CHECK_EXPIRATION=OFF;
-- CREATE LOGIN i2b2workdata WITH PASSWORD = 'demouser',CHECK_POLICY=OFF,CHECK_EXPIRATION=OFF;
-- USE i2b2;CREATE USER i2b2demodata FOR LOGIN i2b2demodata;
-- USE i2b2;CREATE USER i2b2hive FOR LOGIN i2b2hive;
-- USE i2b2;CREATE USER i2b2imdata FOR LOGIN i2b2imdata;
-- USE i2b2;CREATE USER i2b2metadata FOR LOGIN i2b2metadata;
-- USE i2b2;CREATE USER i2b2pm FOR LOGIN i2b2pm;
-- USE i2b2;CREATE USER i2b2workdata FOR LOGIN i2b2workdata;
-- USE i2b2;GRANT Control TO i2b2demodata;
-- USE i2b2;GRANT Control TO i2b2hive;
-- USE i2b2;GRANT Control TO i2b2imdata;
-- USE i2b2;GRANT Control TO i2b2metadata;
-- USE i2b2;GRANT Control TO i2b2pm;
-- USE i2b2;GRANT Control TO i2b2workdata;
